In [20]:
# import libraries needed
import pandas as pd
import numpy as np

# Assignment 1: Series Basics

The code has been previded to create an array, `oil_array` from a dataframe column. 

* Convert `oil_array` into a Pandas Series, called `oil_series`. Give it a name!
* Return the name, dtype, size, and index of `oil_series`.

Take the mean of the values array. 

Then, convert the series to integer datatype and recalculate the mean. 


In [41]:
oil = pd.read_csv("../retail/oil.csv").dropna()
oil

date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [21]:
# create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("../retail/oil.csv").dropna()

# Grab 100 rows of oil prices
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])

oil_array

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

In [41]:
oil_array.size

100

In [8]:
oil_series = pd.Series(oil_array, name="Oil Series")

In [15]:
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...  
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: Oil Series, Length: 100, dtype: float64

In [14]:
oil_series.values

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

In [25]:
# Return dtype oil_series
oil_series.dtype

dtype('float64')

In [21]:
# Return the name, dtype, size, and index of oil_series
oil_series.size

100

In [22]:
# Return the name, dtype, size, and index of oil_series
oil_series.name

'Oil Series'

In [24]:
# Return the name, dtype, size, and index of oil_series
oil_series.index

RangeIndex(start=0, stop=100, step=1)

In [30]:
# 
# Take the mean of the values array.
# 
oil_series.values.mean()

51.128299999999996

In [35]:
# 
# Then, convert the series to integer datatype 
#  and recalculate the mean.
# 

oil_series = oil_series.astype("int")
oil_series.dtype

dtype('int64')

In [37]:
# # 
# Then, convert the series to integer datatype 
#  and recalculate the mean.
# 
oil_series.values.mean()

50.66

In [16]:
# extract date column from oil DataFrame and grab first 100 rows

dates = pd.Series(oil["date"]).iloc[1000:1100]

In [17]:
dates

1035    2016-12-20
1036    2016-12-21
1037    2016-12-22
1038    2016-12-23
1040    2016-12-27
           ...    
1135    2017-05-09
1136    2017-05-10
1137    2017-05-11
1138    2017-05-12
1139    2017-05-15
Name: date, Length: 100, dtype: object

# Assignment 2:  Accessing Series Data

* Set the date series, which has been created below, to be the index of the oil price series created in assignment 1.


* Then, take the mean of the first 10 and last 10 prices of the series.


* Finally, grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.

In [1]:
# Assignment 2:  Accessing Series Data

* Set the date series, which has been created below, to be the index of the oil price series created in assignment 1.


* Then, take the mean of the first 10 and last 10 prices of the series.


* Finally, grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.


SyntaxError: invalid syntax (103327911.py, line 3)

In [25]:
# extract date column from oil DataFrame and grab first 100 rows

dates = pd.Series(oil["date"]).iloc[1000:1100]

In [26]:
oil_series.index = dates

In [27]:
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: Oil Series, Length: 100, dtype: float64

In [29]:
oil_series_first_10 = oil_series.head(10)
oil_series_first_10

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
2016-12-28    54.01
2016-12-29    53.80
2016-12-30    53.75
2017-01-03    52.36
2017-01-04    53.26
Name: Oil Series, dtype: float64

In [38]:
oil_series_first_10.iloc[:10]

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
2016-12-28    54.01
2016-12-29    53.80
2016-12-30    53.75
2017-01-03    52.36
2017-01-04    53.26
Name: Oil Series, dtype: float64

In [39]:
oil_series_first_10.loc[:"2017-01-04 "]

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
2016-12-28    54.01
2016-12-29    53.80
2016-12-30    53.75
2017-01-03    52.36
2017-01-04    53.26
Name: Oil Series, dtype: float64

In [31]:
oil_series_first_10.mean()

52.765

In [30]:
oil_series_last_10 = oil_series.tail(10)
oil_series_last_10

date
2017-05-02    47.65
2017-05-03    47.79
2017-05-04    45.55
2017-05-05    46.23
2017-05-08    46.46
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: Oil Series, dtype: float64

In [32]:
oil_series_last_10.mean()

47.129999999999995

In [37]:
# grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.

set_default_index = oil_series.loc["2017-01-01":"2017-01-07"]
set_default_index.reset_index(drop=True)

0    52.36
1    53.26
2    53.77
3    53.98
Name: Oil Series, dtype: float64

# Assignment 3: Sorting and Filtering Series

* First, get the 10 lowest prices from the data. 
* Sort the 10 lowest prices by date, starting with the most recent and ending with the oldest price.

* Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.

In [65]:
# list of dates to be used to solve bullet 3

dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-06",
    "2017-03-05",
    "2017-02-12",
    "2017-03-21",
    "2017-04-14",
    "2017-04-15",
]

In [55]:
lowest_price = oil_series.sort_values().iloc[:10]
lowest_price

date
2017-05-04    45.55
2017-05-09    45.84
2017-05-05    46.23
2017-05-08    46.46
2017-03-23    47.00
2017-03-21    47.02
2017-03-27    47.02
2017-03-14    47.24
2017-05-10    47.28
2017-03-22    47.29
Name: Oil Series, dtype: float64

In [56]:
lowest_price_date = lowest_price.sort_index(ascending=False)
lowest_price_date

date
2017-05-10    47.28
2017-05-09    45.84
2017-05-08    46.46
2017-05-05    46.23
2017-05-04    45.55
2017-03-27    47.02
2017-03-23    47.00
2017-03-22    47.29
2017-03-21    47.02
2017-03-14    47.24
Name: Oil Series, dtype: float64

In [52]:
lowest_price_date.loc[lowest_price < 50]

date
2017-03-14    47.24
2017-03-21    47.02
2017-03-22    47.29
2017-03-23    47.00
2017-03-27    47.02
2017-05-04    45.55
2017-05-05    46.23
2017-05-08    46.46
2017-05-09    45.84
2017-05-10    47.28
Name: Oil Series, dtype: float64

In [61]:
# Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.

new_oil_series = lowest_price_date.index
new_oil_series.isin(dates)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [70]:
mask = (new_oil_series.isin(dates)) & (lowest_price <= 50)
lowest_price_date.loc[mask]

date
2017-05-10    47.28
Name: Oil Series, dtype: float64


# Assignment 4: Series Operations

* Increase the prices in the oil series by 10%, and add an additional 2 dollars per barrel on top of that.

* Then, create a series that represents the difference between each price and max price.

* Finally, extract the month from the string dates in the index and store them as an integer in their own series.

In [85]:
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: Oil Series, Length: 100, dtype: float64

In [87]:
oil_series * 1.1 + 2

date
2016-12-20    59.442
2016-12-21    58.584
2016-12-22    59.178
2016-12-23    59.211
2016-12-27    60.102
               ...  
2017-05-09    52.424
2017-05-10    54.008
2017-05-11    54.591
2017-05-12    54.613
2017-05-15    55.746
Name: Oil Series, Length: 100, dtype: float64

In [89]:
max_price = oil_series.max()
max_price

54.48

In [91]:
(oil_series - max_price) / max_price

date
2016-12-20   -0.041483
2016-12-21   -0.055800
2016-12-22   -0.045888
2016-12-23   -0.045338
2016-12-27   -0.030470
                ...   
2017-05-09   -0.158590
2017-05-10   -0.132159
2017-05-11   -0.122430
2017-05-12   -0.122063
2017-05-15   -0.103157
Name: Oil Series, Length: 100, dtype: float64

In [92]:
month = oil_series.index
month

Index(['2016-12-20', '2016-12-21', '2016-12-22', '2016-12-23', '2016-12-27',
       '2016-12-28', '2016-12-29', '2016-12-30', '2017-01-03', '2017-01-04',
       '2017-01-05', '2017-01-06', '2017-01-09', '2017-01-10', '2017-01-11',
       '2017-01-12', '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25', '2017-01-26',
       '2017-01-27', '2017-01-30', '2017-01-31', '2017-02-01', '2017-02-02',
       '2017-02-03', '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09',
       '2017-02-10', '2017-02-13', '2017-02-14', '2017-02-15', '2017-02-16',
       '2017-02-17', '2017-02-21', '2017-02-22', '2017-02-23', '2017-02-24',
       '2017-02-27', '2017-02-28', '2017-03-01', '2017-03-02', '2017-03-03',
       '2017-03-06', '2017-03-07', '2017-03-08', '2017-03-09', '2017-03-10',
       '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16', '2017-03-17',
       '2017-03-20', '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24',

In [99]:
month = month.str[5:7].astype("int")

In [100]:
pd.Series(month)

0     12
1     12
2     12
3     12
4     12
      ..
95     5
96     5
97     5
98     5
99     5
Name: date, Length: 100, dtype: int64

# Assignment 5: Series Aggregations

* Calculate the sum and mean of prices in the month of March. 

* Next, calculate how many prices were recorded in January and February.

* Then, calculate the 10th and 90th percentiles across all data.

* Finally, how often did integer dollar value (e.g. 51, 52) occur in the data? Normalize this to a percentage.   

In [137]:
oil_series = pd.Series(oil_array, name="Oil Series")
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...  
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: Oil Series, Length: 100, dtype: float64

In [138]:
oil_series[oil_series.index.str[6:7]]

AttributeError: Can only use .str accessor with string values!

In [111]:
oil_series

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

# Assignment 6: Missing Data

There were some erroneous prices in our data, so they were filled in with missing values.

Can you confirm the number of missing values in the price column? 

Once you’ve done that, fill the prices in with the median of the oil price series.


In [ ]:
# Fill in two values with missing data

oil_series = oil_series.where(~oil_series.isin([51.44, 47.83]), pd.NA)

# Exercise 7: Apply and Where

Write a function that outputs ‘buy’ if price is less than the 90th percentile and ‘wait’ if it’s not. Apply it to the oil series.

Then, create a series that multiplies price by .9 if the date is ‘2016-12-23’ or ‘2017-05-10’, and 1.1 for all other dates. 